joy_node:
  ros__parameters:
    device_id: 0
    dead_zone: 0.05
    auto_repeat_rate: 20.0

teleop_node:
  ros__parameters:
    axis_linear:
      x: 1
      # x: 7
    scale_linear:
      x: .6
    scale_linear_turbo:
      x: 1.5
    
    axis_angular:
      yaw: 0
      # yaw: 6
    scale_angular:
      yaw: 1.
    scale_angular_turbo:
      yaw: 1.5
    
    enable_button: 0
    enable_turbo_button: 1

    deadzone: 0.1

    require_enable_button: true
